### PR TITLE
Various fixes and small enhancements

### PR DESCRIPTION
**Pull request by Toilal**
This fix some issues that I think are mainly related to changes in dependencies and CFSSL api since this library was initialy written.

### CODE REVIEW

**Review by lasley — CHANGES_REQUESTED** [review]
Awesome thanks @Toilal!

Code looks 👍 , but Travis is failing.

**Comment by Toilal** [comment]
I'll fix tests tomorrow

**Comment by Toilal** [comment]
I've bring back 100% code coverage ! :)

I think it's ready to merge. 

I've made another change today to allow raw API data structures instead of Domain objects (RequestCertificate, Host, SubjectInfo, and so one). They can now be replaced with string or dict, this will also work.

**Comment by Toilal** [comment]
Maybe you could add Python 3 version in `.travis.yml` as it's now supported.

Could you perform a pipy release after merge ?

**Comment by lasley** [comment]
> I've made another change today to allow raw API data structures instead of Domain objects (RequestCertificate, Host, SubjectInfo, and so one). They can now be replaced with string or dict, this will also work.

Good idea; I like.

> Maybe you could add Python 3 version in .travis.yml as it's now supported.

I noticed your change in 2a4ed8a and created #21 to make the Travis change. Thanks for that!

> Could you perform a pipy release after merge ?

Definitely

**Review by lasley — APPROVED** [review]
Thanks @Toilal!

**Pull request merged**
